<?php
/**
 * Language labels for plugin "tx_vjchat_pi1"
 *
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'session_not_found' => 'Session not found. Problably it was removed.',
		'sessions_not_found' => 'No sessions.',
		'entries_not_found' => 'No messages.',
		'back' => 'Back',	
		'new_message' => 'New Message',
		'submit_message' => 'Send',
		'back_to_rooms' => 'Back to rooms',
		'back_to_sessions' => 'Back to sessions',
		'user_in_chat' => 'user in chat room.',
		'no_user_in_chat' => 'No user in chat room.',
		'max_user' => 'Maximum usercount',
		'error_access_denied' => 'Action not allowed. Access denied.',
		'error_room_access_denied' => 'You are not allowed to access this chat room. Please login.',
		'error_room_full' => 'Room is full. Maximum amount of users is reached.',
		'error_room_not_found' => 'Room not found. Probably it was removed.',
		'error_kicked' => 'You are banned from this room for %d minutes.',
		'error_banned' => 'You are banned from this room.',
		'error_not_invited' => 'This is a private chat room and can only be entered after an invitation.',		
		'message_committed' => 'Message #%d committed',
		'error_commit' => 'An error occurred. Maybe message was already committed.',
		'enter_chat' => 'Enter Chat',
		'leave_chat' => 'Leave Chat',
		'new_window' => 'New window',
		'close_window' => 'Close window',
		'sessions' => 'sessions',
		'experts' => 'Expert(s) online:',
		'superusers' => 'Superuser(s) online:',
		'moderators' => 'Moderator(s) online:',
		'users' => 'User online:',
		'system_name' => '*',
		'hide_message' => 'Hide message',
		'commit_message' => 'Commit message',		
		'store_message' => 'Store message',
		'user_enters_chat' => '%s enters chat.',
		'user_leaves_chat' => '%s leaves chat.',
		'after_welcome_message' => 'If you need help try \'/help\'',
		'command_title' => '--== Chat Commands ==--',
		'command_header' => 'Welcome to our chat. One tip for you: Press CTRL+RETURN to send a multiline message. The following commands you can use during the chat:<br/>',
		'command_help' => 'Shows this screen.',
		'command_msg' => 'Sends a private message.',		
		'command_smileys' => 'Shows all available emoticons with the corresponding code.',
		'command_roomlist' => 'Shows all online users in other rooms.',
		'command_who' => 'Shows the usernames of all people in the current room.',
		'command_whois' => 'Detailed information about a user.',
		'command_kick' => 'Let you remove a user temporary from the current room with an optional reason. You can call /redeem to undo that.',
		'command_kick_param_time' => 'The user will be banned this time in minutes.',
		'command_kick_ok' => '%s was kicked by %s for %d minutes.',
		'command_kick_reason' => 'Reason: \'%s\'',
		'command_ban' => 'Add user to banned list.',
		'command_ban_ok' => '%s was banned by %s.',
		'command_ban_reason' => 'Reason: \'%s\'',
		'command_redeem' => 'Revive user if he or she were kicked or removes user from banned list.',
		'command_redeem_ok' => '%s was redeemed by %s.',
		'command_redeem_reason' => 'Reason: \'%s\'',
		'command_quit' => 'Let you quit the current room with an optional message.',
		'command_quit_ok' => '%s quits.',
		'command_quit_reason' => 'Reason: \'%s\'',
		'command_makesession' => 'Creates a session.',
		'command_makesession_param_name' => 'A name for the session',
		'command_makesession_param_firstid' => 'Id of the first message',
		'command_makesession_param_lastid' => 'Id of the last message',
		'command_makeexpert' => 'Adds an user to the expert list',
		'command_makeuser' => 'Removes an user from the expert list',		
		'command_cleanup' => 'Deletes all entries of this room that do not belong to a session.',		
		'command_cleanupall' => 'Deletes all entries of all rooms that do not belong to a session.',				
		'command_setstatus' => 'Toggles the status of the user (e.g. \'hidden\')',										
		'command_error_user_not_found' => 'User \'%s\' not found',
		'command_parameter_wrong' => 'Parameter %s wrong. Should be %s',
		'command_not_found' => '%s command not found enter \'/help\'',
		'command_param_userid' => '#UserId or Username',
		'command_param_roomid' => 'RoomId',
		'command_param_reason' => 'A reason',
		'command_param_status' => 'E.g. \'hidden\'',
		'command_param_message' => 'A message',
		'command_newroom' => 'Creates a new private room. User can then be added by /invite',
		'command_newroom_param_name' => 'A name for the new room',
		'command_newroom_param_description' => 'A description for the new room.',				
		'command_newroom_room_default_title' => 'Private room of %s',
		'command_newroom_room_default_description' => 'This private chat room you can enter if you received an invitation of %s.',		
		'command_newroom_ok' => 'A new room *%s* has been created.',
		'command_invite' => 'Invites a user to your private room.',
		'command_invite_default_message' => '*%s* invites *%s* to enter his or her private room *%s*.',
		'command_invite_enter_room' => 'Enter room',
		'command_invite_enter_room_ok' => '*%s* is now authorized to enter this room. %d invitations have been sent.',		
		'command_invite_user_not_online' => '*%s* is not a member of any room. This invitation could not be sent.',
		'command_recent_invite' => 'Invites a user to the latest room created by the current user.',
		'command_setroomstatus' => 'Toggles the status of the room (e.g. \'hidden\', \'private\')',
		'chatbutton.bold' => 'Bold [b]text[/b] or *text*',
		'chatbutton.italic' => 'Italic [i]text[/i]',
		'chatbutton.underlined' => 'Underlined [u]text[/u] or _text_',
		'chatbutton.stroke' => 'Stroke [s]text[/s]',
		'chatbutton.email' => 'E-Mail [email]text[/email]',
		'chatbutton.http' => 'Web-URL [url]text[/url]',
		'chatbutton.clock_on' => 'Show time',
		'chatbutton.clock_off' => 'Hide time',
		'chatbutton.usercolor_on' => 'Colorize nicknames',
		'chatbutton.usercolor_off' => 'Remove colors for nicknames',
		'chatbutton.smilies_on' => 'Show smilies',
		'chatbutton.smilies_off' => 'Hide smilies',
		'chatbutton.colors_on' => 'Show message styles',
		'chatbutton.colors_off' => 'Show message styles',
		'chatbutton.help' => 'Help - Shows available chat commands',
		'chatbutton.autofocus_on' => 'Autofocus: brings the cat window to front if there are new messages.',
		'chatbutton.autofocus_off' => 'Switch off autofocus.',
		'chatbutton.enablesound_on' => 'Sound on',
		'chatbutton.enablesound_off' => 'Sound off',
		'privateMsgUsernamens' => 'From %s to %s',
		'userlistPMInfo' => 'Send a private Message to \'%s\'',
		'userlistPRInfo' => 'Open a new room and invite \'%s\'',
		'talktoroomname' => 'Private talk to %s',
		'closed' => 'Closed',
		'loading_message' => 'Loading the chat interface...',
		'snippetsError' => 'An error occured during the chat. You should reload the chat window. Do you want to do this now?',
		
	),
	'de' => Array (
		'session_not_found' => 'Die Sitzung wurde nicht gefunden. M&ouml;glicherweise wurde sie entfernt.',
		'sessions_not_found' => 'Keine Sitzungen vorhanden.',
		'entries_not_found' => 'Keine Nachrichten.',
		'new_message' => 'Neue Nachricht',
		'submit_message' => 'Senden',
		'back_to_rooms' => 'Zur&uuml;ck zur Raum&uuml;bersicht',
		'back_to_sessions' => 'Zur&uuml;ck zur Sitzungs&uuml;bersicht',				
		'user_in_chat' => 'User befinden sich im Chat.',
		'no_user_in_chat' => 'Der Chatraum ist leer.',
		'max_user' => 'Maximale Anzahl von Teilnehmern: ',
		'error_access_denied' => 'Sie sind nicht autorisiert, diese Aktion durchrzuf&uuml;hren.',
		'error_room_access_denied' => 'Sie sind nicht berechtigt, diesen Raum zu betreten oder Eintr&auml;ge einzusehen. Bitte melden Sie sich an.',
		'error_room_full' => 'Der Raum ist voll. Die maximale Anzahl von Nutzern wurde erreicht. Sie werden automatisch in dem Raum eintreten, sobald ein Platz frei wird. Oder versuchen Sie es sp&auml;ter erneut.',
		'error_room_not_found' => 'Der Raum konnte nicht gefunden werden. M&ouml;glicherweise wurde er entfernt.',
		'error_kicked' => 'Sie wurden f&uuml;r diesen Raum gesperrt. Noch %d Minuten.',
		'error_banned' => 'Sie wurden für diesen Raum gesperrt.',
		'error_not_invited' => 'Dies ist ein privater Chatraum und kann nur nach einer Einladung betreten werden.',
		'message_committed' => 'Nachricht #%d wurde freigegeben',
		'error_commit' => 'Nachricht konnte nicht freigegeben werden. Vielleicht bereits freigegeben.',
		'enter_chat' => 'Chat beitreten',
		'leave_chat' => 'Chat verlassen',
		'new_window' => 'Neues Fenster',		
		'close_window' => 'Fenster schließen',
		'sessions' => 'Sitzungen protokolliert',
		'experts' => 'Experte(n) online:',
		'superusers' => 'Superuser online:',		
		'moderators' => 'Moderator(en) online:',
		'users' => 'User online:',		
		'system_name' => '*',
		'hide_message' => 'Nachricht verstecken',
		'commit_message' => 'Nachricht freischalten',		
		'store_message' => 'Nachricht zur&uuml;ckstellen',
		'user_enters_chat' => '%s betritt den Raum.',
		'user_leaves_chat' => '%s verl&auml;sst den Raum.',		
		'after_welcome_message' => 'F&uuml;r Hilfe geben Sie bitte ein: \'/help\'',
		'command_title' => '--== Chat Befehle ==--',
		'command_header' => 'Willkommen zu unserem Chat. Tipp: Dr&uuml;cken STRG+ENTER, um einen Zeilenumbruch zu erzeugen. Folgende Befehle stehen w&auml;hrend des Chats zu Verf&uuml;gung:<br/>',
		'command_help' => 'Zeigt die m&ouml;glichen Befehle an.',
		'command_msg' => 'Sendet eine private Nachricht.',
		'command_roomlist' => 'Zeigt die User der anderen Chatr&auml;ume.',		
		'command_smileys' => 'Zeigt die verf&uuml;gbaren Icons mit den jeweiligen Shortcuts.',		
		'command_who' => 'Zeigt eine Liste &uuml;ber die am Chat teilnehmenden Nutzer.',
		'command_whois' => 'Zeigt Details &uuml;ber einen Nutzer.',
		'command_kick' => 'Entfernt einen Nutzer f&uuml;r eine bestimmte Zeit. Mit \'/redeem\' kann diese Aktion r&uuml;ckg&auml;ngig gemacht werden.',
		'command_kick_param_time' => 'Anzahl der Minuten f&uuml;r die der Nutzer gesperrt wird.',
		'command_kick_ok' => '%s wurde entfernt von %s f&uuml;r %d Minuten.',
		'command_kick_reason' => 'Grund: \'%s\'',
		'command_ban' => 'Entfernt einen Nutzer vom Raum f&uuml;r unbestimmte Zeit.',
		'command_ban_ok' => '%s wurde gesperrt von %s.',
		'command_ban_reason' => 'Grund: \'%s\'',
		'command_redeem' => 'Entsperrt einen Nutzer f&uuml;r den aktuellen Raum.',
		'command_redeem_ok' => '%s wurde entsperrt von %s.',
		'command_redeem_reason' => 'Grund: \'%s\'',
		'command_quit' => 'Den Raum mit einer optionalen Nachricht verlassen.',
		'command_quit_ok' => '%s verl&auml;sst den Raum.',
		'command_quit_reason' => 'Grund: \'%s\'',
		'command_makesession' => 'Erstellt ein Chat-Protokoll.',
		'command_makesession_param_name' => 'Ein Name f&uuml;r das Protokoll.',
		'command_makesession_param_firstid' => 'Id der ersten Nachricht',
		'command_makesession_param_lastid' => 'Id der letzten Nachricht',
		'command_makeexpert' => 'Setzt einen Nutzer auf die Experten-Liste',
		'command_makeuser' => 'Entfernt einen Nutzer von der Experten-Liste',		
		'command_cleanup' => 'L&ouml;scht alle Eintr&auml;ge dieses Raumes, die nicht zu einer Session geh&ouml;ren.',
		'command_cleanupall' => 'L&ouml;scht alle Eintr&auml;ge aller Raumes die zu keiner Session geh&ouml;ren.',						
		'command_setstatus' => '&Auml;ndert den Status des Nutzer (z.B. \'hidden\')',								
		'command_error_user_not_found' => 'User \'%s\' nicht gefunden',
		'command_parameter_wrong' => 'Parameter %s falsch. Sollte sein %s',
		'command_not_found' => 'Befehl \'%s\' nicht gefunden. Geben Sie \'/help\', um eine Liste m&ouml;glicher Befehle zu erhalten.',
		'command_param_userid' => '#UserId oder Username',
		'command_param_roomid' => 'RaumId',
		'command_param_reason' => 'Ein Grund',
		'command_param_status' => 'Zum Beispiel \'hidden\'',
		'command_param_message' => 'Eine Nachricht',
		'command_newroom' => 'Erstellt einen neuen privaten Raum. Benutzer können anschließend mit /invite eingeladen werden.',
		'command_newroom_param_name' => 'Name für den Raum',
		'command_newroom_param_description' => 'Eine nähere Beschreibung für den Raum.',		
		'command_newroom_room_default_title' => 'Privater Raum von %s',
		'command_newroom_room_default_description' => 'Um diesen privaten Chatraum zu betreten, benötigen Sie eine Einladung von %s.',		
		'command_newroom_ok' => 'Ein neuer Raum *%s* wurde erstellt.',
		'command_invite' => 'Lädt einen User in einen privaten Raum ein.',
		'command_invite_default_message' => '*%s* lädt *%s* in seinen oder ihren Chatraum *%s* ein.',		
		'command_invite_enter_room' => 'Raum betreten',		
		'command_invite_enter_room_ok' => '*%s* darf diesen Raum nun betreten. Die Einladung wurde an %d Räume gesendet.',
		'command_invite_user_not_online' => '*%s* ist in keinem Raum. Die Einladung wurde nicht gesendet.',		
		'command_recent_invite' => 'Lädt einen Nutzer in den zuletzt erstellten Raum ein.',		
		'command_setroomstatus' => 'Ändert den Status eines Raumes (e.g. \'hidden\',\'private\')',
		'chatbutton.bold' => 'Fett [b]text[/b] oder *text*',
		'chatbutton.italic' => 'Kursiv [i]text[/i]',
		'chatbutton.underlined' => 'Unterstrichen [u]text[/u] oder _text_',
		'chatbutton.stroke' => 'Durchgestrichen [s]text[/s]',
		'chatbutton.email' => 'E-Mail [email]text[/email]',
		'chatbutton.http' => 'Web-URL [url]text[/url]',
		'chatbutton.clock_on' => 'Uhrzeit zeigen',
		'chatbutton.clock_off' => 'Uhrzeit verstecken',
		'chatbutton.usercolor_on' => 'Benutzernamen färben',
		'chatbutton.usercolor_off' => 'Benutzernamen nicht färben',
		'chatbutton.smilies_on' => 'Smilies zeigen',
		'chatbutton.smilies_off' => 'Smilies verstecken',
		'chatbutton.colors_on' => 'Nachrichtenstile zeigen',
		'chatbutton.colors_off' => 'Nachrichtenstile verstecken',
		'chatbutton.help' => 'Hilfe - Zeigt die verfügbaren Chat-Befehle an',
		'chatbutton.autofocus_on' => 'Autofokus: bringt das Fenster nach vorn, wenn neue Nachrichten vorhanden sind.',
		'chatbutton.autofocus_off' => 'Autofokus ausschalten.',
		'chatbutton.enablesound_on' => 'Sound an',
		'chatbutton.enablesound_off' => 'Sound off',
		'privateMsgUsernamens' => 'PM von %s an %s',
		'userlistPMInfo' => 'Eine private Nachricht an \'%s\' schicken',
		'userlistPRInfo' => 'Einen neuen Raum öffnen und \'%s\' einladen.',
		'talktoroomname' => 'Privater Raum mit %s',		
		'closed' => 'Geschlossen',
		'loading_message' => 'Die Chat-Oberfläche wird geladen...',
		'snippetsError' => 'Es ist ein Fehler aufgetreten. Sie sollten das Chat-Fenster neu laden. Möchten Sie es jetzt neu laden?',
	),
	'dk' => array (
		'after_welcome_message' => 'Hvis du har brug for hj&aelig;lp, s&aring; skriv \'/help\'',
		'back' => 'Tilbage',
		'back_to_rooms' => 'Tilbage til oversigt over chatrum',
		'back_to_sessions' => 'Tilbage til sessioner',
		'command_ban' => 'Tilf&oslash;j bruger til listen over brugere der er n&aelig;gtet adgang.',
		'command_ban_ok' => '%s var n&aelig;gtet adgang af %s.',
		'command_ban_reason' => 'Grund: \'%s\'',
		'command_cleanup' => 'Slet alle entries af dette rum som ikkke tilh&oslash;rer en session.',
		'command_cleanupall' => 'Slet alle entries af alle rum som ikkke tilh&oslash;rer en session.',
		'command_error_user_not_found' => 'Brugeren \'%s\' blev ikke fundet',
		'command_header' => 'Velkommen til vores Chat.<br /><br />Et lille tip: Tryk CTRL+RETURN for at sende beskeder p&aring; flerer linier.<br /><br />Du kan bruge f&oslash;lgende kommandoer under chat:<br />',
		'command_help' => 'Viser dette sk&aelig;rmbillede.',
		'command_kick' => 'Fjern en bruger midlertidigt fra en rum, med en optional grund. Med kommandoen \'/redeem\' kan du fortryde handlingen.',
		'command_kick_ok' => '%s blev smidt ud af %s i %d minutter.',
		'command_kick_param_time' => 'Brugeren vil blive n&aelig;gtet adgang i dette antal minutter.',
		'command_kick_reason' => 'Grund: \'%s\'',
		'command_makeexpert' => 'Tilf&oslash;j en bruger til listen over eksperter',
		'command_makesession' => 'Opretter en session.',
		'command_makesession_param_firstid' => 'Id p&aring; den f&oslash;rste besked',
		'command_makesession_param_lastid' => 'Id p&aring; den sidste besked',
		'command_makesession_param_name' => 'Et navn for denne session',
		'command_makeuser' => 'Fjerner en bruger fra listen over eksperter',
		'command_not_found' => 'Kommandoen \'%s\' findes ikke. Skriv \'/help\' for liste over kommandoer.',
		'command_param_reason' => 'En grund',
		'command_param_userid' => 'BrugerId eller Brugernavn',
		'command_parameter_wrong' => 'Parameteret %s er forkert. Det burde v&aelig;re %s',
		'command_quit' => 'Forlad rummet med en optional besked.',
		'command_quit_ok' => '%s forlader rummet.',
		'command_quit_reason' => 'Grund: \'%s\'',
		'command_redeem' => 'Fjerner bruger fra liste over brugere der er n&aelig;gtet adgang.',
		'command_redeem_ok' => '%s har f&aring;et sin adgang tilbage af %s.',
		'command_redeem_reason' => 'Grund: \'%s\'',
		'command_roomlist' => 'Viser alle online brugere i et rum.',
		'command_smileys' => 'Viser alle tilg&aelig;ngelige emoticons med deres tilsvarende kode.',
		'command_title' => '--== Chat Kommandoer ==--',
		'command_who' => 'Viser brugernavn p&aring; alle brugere i det nuv&aelig;rende rum.',
		'command_whois' => 'Detaljeret information om en bruger.',
		'enter_chat' => '&Aring;ben chat',
		'entries_not_found' => 'Ingen beskeder.',
		'error_access_denied' => 'Handling ikke tilladt. Adgang n&aelig;gtet.',
		'error_banned' => 'Du er blevet n&aelig;gtet adgang til dette rum.',
		'error_kicked' => 'Du er blevet n&aelig;gtet adgang til dette rum i %s minutter.',
		'error_room_access_denied' => 'Du har ikke tilladelse til at &aring;bne dette chatrum. V&aelig;r venlig at logge ind.',
		'error_room_full' => 'Rummet er fyldt. Maksimum antal brugere er n&aring;et.',
		'error_room_not_found' => 'Rummet blev ikke fundet. Der er formentlig fjernet.',
		'experts' => 'Ekspert(er) online:',
		'hide_message' => 'Skjul besked',
		'leave_chat' => 'Forlad chat',
		'max_user' => 'Maximum brugerantal',
		'moderators' => 'Moderator(er) online:',
		'new_message' => 'Ny besked',
		'no_user_in_chat' => 'Ingen bruger i chat rum.',
		'session_not_found' => 'Sessionen blev ikke fundet. Den er formentlig flyttet.',
		'sessions' => 'sessioner',
		'sessions_not_found' => 'Ingen sessioner',
		'store_message' => 'Gem besked',
		'submit_message' => 'Send',
		'system_name' => '*',
		'user_enters_chat' => '%s er i chat.',
		'user_in_chat' => 'bruger i chat rum.',
		'user_leaves_chat' => '%s forlader chat.',
		'command_setstatus' => '&AElig;ndre status for bruger (f.eks. \'hidden\')',
		'commit_message' => 'Send besked',
		'error_commit' => 'En fejl er opst&aring;et. M&aring;ske er beskeden allerede sendt.',
		'message_committed' => 'Besked #%d er sendt',
	),
	'no' => Array (
	),
	'it' => Array (
	),
	'fr' => Array (
	),
	'es' => Array (
	),
	'nl' => Array (
		'session_not_found' => 'Sessie niet gevonden. Waarschijnlijk is deze verwijderd.',
		'sessions_not_found' => 'Geen sessies gevonden.',
		'entries_not_found' => 'Geen berichten gevonden.',
		'back' => 'Terug',
		'new_message' => 'Nieuw Bericht',
		'submit_message' => 'Verstuurd',
		'back_to_rooms' => 'Terug naar de ruimtes',
		'back_to_sessions' => 'Terug naar de sessies',
		'user_in_chat' => 'gebruikers in de chat ruimte.',
		'no_user_in_chat' => 'Geen gebruikers in de chat ruimte.',
		'max_user' => 'Maximale gebruikers',
		'error_access_denied' => 'Actie niet toegestaan. Toegang geweigerd.',
		'error_room_access_denied' => 'Je hebt geen toegang tot de chat ruimte. Log eerst in.',
		'error_room_full' => 'Ruimte is vol. Maximaal aantal gebruikers is bereikt.',
		'error_room_not_found' => 'Ruimte niet gevonden. Waarschijnlijk is deze verwijderd.',
		'error_kicked' => 'Je bent gebanned in deze ruimte voor %d minuten.',
		'error_banned' => 'Je bent gebanned voor deze ruimte.',
		'message_committed' => 'Bericht #%d is goedgekeurd',
		'error_commit' => 'Er is een error opgetreden. Waarschijnlijk is het bericht al goedgekeurd.',
		'enter_chat' => 'Enter Chat',
		'leave_chat' => 'Verlaat Chat',
		'sessions' => 'sessies',
		'experts' => 'Expert(s) online:',
		'moderators' => 'Moderator(s) online:',
		'system_name' => '*',
		'hide_message' => 'Verberg bericht',
		'commit_message' => 'Keur bericht goed',
		'store_message' => 'Sla bericht op',
		'user_enters_chat' => '%s komt binnen in de chat.',
		'user_leaves_chat' => '%s verlaat de chat.',
		'after_welcome_message' => 'Voor hulp type: \'/help\'',
		'command_title' => '--== Chat Commando\'s ==--',
		'command_header' => 'Welkom op onze chat. Tip: Druk op CTRL+RETURN om meerdere regels te versturen. De volgende commando\'s zijn beschikbaar tijdens de chat:<br/>',
		'command_help' => 'Laat dit scherm zien.',
		'command_smileys' => 'Laat alle smilies zien met bijbehorende code.',
		'command_roomlist' => 'Laat alle gebruikers zin in de andere ruimtes.',
		'command_who' => 'Laat alle gebruikers zien in deze ruimte.',
		'command_whois' => 'Gedetailleerde informatie over een gebruiker.',
		'command_kick' => 'Verwijderd een gebruiker tijdelijk van de chat. Eventueel met een reden. Door middel van /redeem kan dit ongedaan worden gemaakt.',
		'command_kick_param_time' => 'De gebruiker zal deze tijd worden gebanned in minuten.',
		'command_kick_ok' => '%s is gebanned door %s voor %d minuten.',
		'command_kick_reason' => 'Reden: \'%s\'',
		'command_ban' => 'Voeg gebruiker toe aan de ban lijst.',
		'command_ban_ok' => '%s is gebanned door %s.',
		'command_ban_reason' => 'Reden: \'%s\'',
		'command_redeem' => 'Activeer gebruiker die gekicked was of verwijder een gebruiker van de ban lijst.',
		'command_redeem_ok' => '%s is bevrijdt door %s.',
		'command_redeem_reason' => 'Reden: \'%s\'',
		'command_quit' => 'Verlaat de huidige ruimte. Eventueel met een reden.',
		'command_quit_ok' => '%s verlaat de chat.',
		'command_quit_reason' => 'Reden: \'%s\'',
		'command_makesession' => 'Maakt een sessie.',
		'command_makesession_param_name' => 'Een naam voor de sessie',
		'command_makesession_param_firstid' => 'Id van het eerste bericht',
		'command_makesession_param_lastid' => 'Id van het laatste bericht',
		'command_makeexpert' => 'Voeg een gebruiker toe aan de Expert lijst',
		'command_makeuser' => 'Verwijderd een gebruiker van de Expert lijst',		
		'command_cleanup' => 'Verwijderd alle berichten in deze ruimte die geen sessie hebben.',	
		'command_cleanupall' => 'Verwijderd alle berichten in alle ruimtes die geen sessie hebben.',	
		'command_setstatus' => 'Veranderd de status van een gebruiker. (bijvoorbeeld. \'hidden\')',	
		'command_error_user_not_found' => 'Gebruiker \'%s\' is niet gevonden',
		'command_parameter_wrong' => 'Parameter %s is verkeerd. Het zou %s moeten zijn.',
		'command_not_found' => '%s commando is niet gevonden. Gebruik de help functie d.m.v het \'/help\' commando',
		'command_param_userid' => '#UserId of Gebruikersnaam',
		'command_param_reason' => 'Een reden',	
	),
	'cz' => Array (
	),
	'pl' => Array (
	),
	'si' => Array (
	),
	'fi' => Array (
	),
	'tr' => Array (
	),
	'se' => Array (
	),
	'pt' => Array (
	),
	'ru' => Array (
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
	),
	'hu' => Array (
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
	'eo' => Array (
	),
	'my' => Array (
	),
);
?>